-- WAP Migo - Jornada do visitante
-- Execute este arquivo UMA VEZ no SQL Editor do Supabase.

create table if not exists public.jornada_eventos (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  evento text not null,
  pagina text,
  dados jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists jornada_eventos_session_idx
  on public.jornada_eventos (session_id);

create index if not exists jornada_eventos_criado_em_idx
  on public.jornada_eventos (criado_em desc);

alter table public.jornada_eventos enable row level security;

drop policy if exists "Permitir registro da jornada" on public.jornada_eventos;
create policy "Permitir registro da jornada"
on public.jornada_eventos
for insert
to anon, authenticated
with check (true);

drop policy if exists "Permitir leitura administrativa da jornada" on public.jornada_eventos;
create policy "Permitir leitura administrativa da jornada"
on public.jornada_eventos
for select
to authenticated
using (true);
